### ISSUE TITLE
Missing urlencode of fact values

### ISSUE THREAD

**Issue by olavmrk** [voxpupuli/pypuppetdb#67]
When looking up nodes by fact values using `db.facts(name, value)`, pypuppetdb doesn't encode the value in the request URL, which results in PuppetDB returning a "404 Not Found" error.

For example:
```
for r in db.facts('macaddress', '02:42:ec:94:80:f0'):
    print(r)
```
triggers the following exception:
```
Traceback (most recent call last):
  File "test_mac_lookup.py", line 10, in <module>
    for r in db.facts('macaddress', '02:42:ec:94:80:f0'):
  File "/home/olavmo/test_mac_lookup/.ve/lib/python3.4/site-packages/pypuppetdb/api/__init__.py", line 531, in facts
    facts = self._query('facts', path=path, **kwargs)
  File "/home/olavmo/test_mac_lookup/.ve/lib/python3.4/site-packages/pypuppetdb/api/__init__.py", line 332, in _query
    r.raise_for_status()
  File "/home/olavmo/test_mac_lookup/.ve/lib/python3.4/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://puppetdb.uninett.no:8081/pdb/query/v4/facts/macaddress/02:42:ec:94:80:f0
```

If we manually escape the value, it works:
```
for r in db.facts('macaddress', '02%3a42%3aec%3a94%3a80%3af0'):
    print(r)
```
prints:
```
macaddress/dlolamor14.ikt.uninett.no
```

**Comment by corey-hammerton** [comment]
Will have to replace the original solution with urllib quote.
